name: swift-chat-sdk
scm: github.com/pubnub/swift-chat-sdk
version: 0.30.2
schema: 1
changelog:
  - date: 2025-06-12
    version: 0.30.2
    changes:
      - type: feature
        text: "Add `autoModerationId` property in EventContent.Report."
      - type: improvement
        text: "Add PrivacyInfo.xcprivacy."
      - type: improvement
        text: "Remove unused `PubNubSwiftChatSDK_Info.plist` file."
  - date: 2025-05-21
    version: 0.30.1
    changes:
      - type: bug
        text: "Update core PubNub Swift SDK dependency."
  - date: 2025-05-14
    version: 0.30.0
    changes:
      - type: feature
        text: "Deprecate `getUnreadMessagesCount(limit:page:filter:sort:)` method in Chat interface."
      - type: feature
        text: "Introduce `fetchUnreadMessagesCounts(limit:page:filter:sort:)` method in Chat interface."
      - type: bug
        text: "Fix the issue with the invalid download URL for files."
      - type: improvement
        text: "Remove code duplication from the `ChatImpl` constructors."
      - type: improvement
        text: "Add thread safety to chat mapping logic."
  - date: 2025-03-25
    version: 0.20.0
    changes:
      - type: feature
        text: "Add async/await counterparts to existing closure-based methods."
      - type: feature
        text: "Add `AsyncStream` counterparts for methods returning `AutoCloseable`."
      - type: feature
        text: "Add a new Test Plan testing async/await methods and streams."
      - type: feature
        text: "Add the new way to create a thread message."
      - type: bug
        text: "Provide a default `ChatConfiguration()` value in the `ChatImpl` constructor."
      - type: bug
        text: "Provide a default value for the `limit` parameter in the Chat's `getUsers(filter:sort:limit:page:completion:)`."
      - type: bug
        text: "Fix `PubNub.MembershipSortField` extension to handle all user sort options properly."
  - date: 2025-03-21
    version: 0.12.0
    changes:
      - type: feature
        text: "Allow users to be invited to public conversations."
  - date: 2025-03-10
    version: 0.11.1
    changes:
      - type: feature
        text: "Enhance entities descriptions with `CustomStringConvertible`."
      - type: feature
        text: "Add an optional `customPushData:` parameter to methods responsible for sending text."
      - type: bug
        text: "Fix the issue with incorrect handling of the APNS device token."
      - type: bug
        text: "The `description` property in `Channel` interface has been replaced with `channelDescription` to avoid conflicts with `CustomStringConvertible`."
      - type: bug
        text: "Retain the caller object by `AutoCloseable` for each entity's non-static methods."
      - type: bug
        text: "Add a more descriptive error message when a chat object is deallocated during initialization."
  - date: 2025-01-28
    version: 0.11.0
    changes:
      - type: feature
        text: "Add the new `update(updateAction:completion:)`method on User entity. This method can be used to update data on the server without losing intermediate updates that might have happened in the time between when the object was last received and updated."
      - type: feature
        text: "Add the ability to mute and unmute users on the Chat instance. There are `chat.mutedUsersManager.mute(userId:completion:)` and `chat.mutedUsersManager.unmuteUser(userId:completion:)` to mute and unmute a user, respectively."
      - type: feature
        text: "Add the option to automatically sync the mute list by enabling `ChatConfiguration.syncMutedUsers`."
      - type: feature
        text: "Add missing function to parse quoted message text into `[MessageElement]`."
      - type: bug
        text: "Fix the problem of overwriting custom data at regular intervals when `storeUserActivityInterval` is enabled."
  - date: 2025-01-23
    version: 0.10.3
    changes:
      - type: bug
        text: "Fix the error when retrieving the unread messages count on the Membership instance."
  - date: 2025-01-14
    version: 0.10.2
    changes:
      - type: bug
        text: "Fix the bug with messages being deleted from Message Persistence."
  - date: 2025-01-09
    version: 0.10.1
    changes:
      - type: bug
        text: "Remove `createUser(user:completion:)` method from the public interface."
      - type: bug
        text: "Add missing `reactionsActionName` computed property."
      - type: improvement
        text: "Documentation enhancements."
  - date: 2025-01-08
    version: 0.10.0
    changes:
      - type: feature
        text: "Add `status` and `type` to Membership."
  - date: 2024-12-18
    version: 0.9.3
    changes:
      - type: bug
        text: "Add missing initialization for `reactionsActionName` property."
      - type: bug
        text: "Add missing `completion:` parameter when sending a text."
      - type: improvement
        text: "Run `swiftformat` to uplift the codebase."
  - date: 2024-12-17
    version: 0.9.2
    changes:
      - type: feature
        text: "Add support for other Apple platforms."
      - type: feature
        text: "Lock moderated messages from editing."
      - type: bug
        text: "Remove `getChannelSuggestions(text:limit:completion:)` method from `Chat` interface."
      - type: bug
        text: "Remove `getUserSuggestions(text:limit:completion:)` method from `Chat` interface."
      - type: bug
        text: "Wrong user suggestion source for message draft created on ThreadChannel."
      - type: bug
        text: "Wrong type of last user activity time stored on the server (precision)."
      - type: improvement
        text: "Moderation events are now sent to a channel prefixed with `PUBNUB_INTERNAL_MODERATION.`."
  - date: 2024-12-05
    version: 0.9.1
    changes:
      - type: feature
        text: "Add third-party dependencies due to Kotlin Multiplatform usage."
      - type: bug
        text: "Add missing userSuggestionSource property."
  - date: 2024-11-06
    version: 0.9.0
    changes:
      - type: feature
        text: "Add Message Draft feature"
      - type: bug
        text: "Return nil for hard delete operations"
      - type: bug
        text: "Add missing reactionsActionName property"
  - date: 2024-10-24
    version: 0.8.2
    changes:
      - type: bug
        text: "Use kmp-chat dependency without pubnub-kotlin submodule"
  - date: 2024-10-22
    version: 0.8.1
    changes:
      - type: bug
        text: "Fix dependency issues for kmp-chat and its submodules"
  - date: 2024-09-25
    version: 0.8.0
    changes:
      - type: feature
        text: "Initial Swift Chat SDK release"
sdks:
  - full-name: PubNub Swift Chat SDK
    short-name: Swift Chat
    artifacts:
      - artifact-type: api-client
        language: Swift
        tier: 1
        tags:
          - Desktop
          - Mobile
        source-repository: https://github.com/pubnub/swift-chat-sdk
        documentation: https://github.com/pubnub/swift-chat-sdk
        distributions:
          - distribution-type: source
            distribution-repository: GitHub release
            package-name: PubNubSwiftChatSDK
            location: https://github.com/pubnub/swift-chat-sdk/archive/refs/tags/0.30.2.zip
            supported-platforms:
              supported-operating-systems:
                iOS:
                  runtime-version:
                    - Swift 5.x
                  minimum-os-version:
                    - iOS 14.0
                  maximum-os-version:
                    - iOS 18.5
                  target-architecture:
                    - arm64
                  target-devices:
                    - iPhone
                    - iPad
                macOS:
                  runtime-version:
                    - Swift 5.x
                  minimum-os-version:
                    - macOS 11.0
                  maximum-os-version:
                    - macOS 15.5
                  target-architecture:
                    - arm64
                    - x86_64
                tvOS:
                  runtime-version:
                    - Swift 5.x
                  minimum-os-version:
                    - tvOS 14.0
                  maximum-os-version:
                    - tvOS 18.5
                  target-architecture:
                    - arm64
                  target-devices:
                    - Apple TV

supported-platforms:
  - version: PubNub Swift Chat SDK
    platforms:
      - iOS 14.0 or higher
      - macOS 11.0 or higher
      - tvOS 14.0 or higher
