name: Automated product release

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  check-release:
    name: Check release required
    if: github.event.pull_request.merged && endsWith(github.repository, '-private') != true
    runs-on:
      group: organization/Default
    outputs:
      release: ${{ steps.check.outputs.ready }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - id: check
        name: Check pre-release completed
        uses: ./.github/.release/actions/actions/checks/release
        with:
          token: ${{ secrets.GH_TOKEN }}
  publish:
    name: Publish package
    needs: check-release
    if: needs.check-release.outputs.release == 'true'
    runs-on:
      group: macos-arm-gh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GH_TOKEN }}
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Setup Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Create Release
        uses: ./.github/.release/actions/actions/services/github-release
        with:
          token: ${{ secrets.GH_TOKEN }}
          jira-api-key: ${{ secrets.JIRA_API_KEY }}
          last-service: true
